In [116]:
# importing libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Data Collection and Processsing

In [117]:
data = pd.read_csv(r"/Users/amani/Downloads/ner_dataset.csv",encoding='unicode_escape')

data.head()

Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [118]:
data.rename({"Sentence #":"Sentence"},axis = 1,inplace= True)

In [119]:
data.head()

Sentence           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [120]:
data.shape

(1048575, 4)

In [121]:
data.isna().sum()

Sentence    1000616
Word             10
POS               0
Tag               0
dtype: int64

In [122]:
# filling all values in sentence columns (forward filling)

data.fillna(method="ffill",inplace = True)
data.head()

Sentence           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1  Sentence: 1             of   IN   O
2  Sentence: 1  demonstrators  NNS   O
3  Sentence: 1           have  VBP   O
4  Sentence: 1        marched  VBN   O

In [123]:
data["Tag"].value_counts()

Tag
O        887908
B-geo     37644
B-tim     20333
B-org     20143
I-per     17251
B-per     16990
I-org     16784
B-gpe     15870
I-geo      7414
I-tim      6528
B-art       402
B-eve       308
I-art       297
I-eve       253
B-nat       201
I-gpe       198
I-nat        51
Name: count, dtype: int64

In [124]:
grouped_data = data.groupby('Sentence').agg({'Word': list, 'POS': list, 'Tag': list}).reset_index()
grouped_data.columns = ['Sentence', 'Word', 'POS', 'Tag']
grouped_data

Sentence                                               Word  \
0          Sentence: 1  [Thousands, of, demonstrators, have, marched, ...   
1         Sentence: 10  [Iranian, officials, say, they, expect, to, ge...   
2        Sentence: 100  [Helicopter, gunships, Saturday, pounded, mili...   
3       Sentence: 1000  [They, left, after, a, tense, hour-long, stand...   
4      Sentence: 10000  [U.N., relief, coordinator, Jan, Egeland, said...   
...                ...                                                ...   
47954   Sentence: 9995  [Opposition, leader, Mir, Hossein, Mousavi, ha...   
47955   Sentence: 9996  [On, Thursday, ,, Iranian, state, media, publi...   
47956   Sentence: 9997  [Following, Iran, 's, disputed, June, 12, elec...   
47957   Sentence: 9998  [Since, then, ,, authorities, have, held, publ...   
47958   Sentence: 9999  [The, United, Nations, is, praising, the, use,...   

                                                     POS  \
0      [NNS, IN, NNS, VBP, VBN, IN, NNP, TO, VB, DT, ...   
1      [JJ, NNS, VBP, PRP, VBP, TO, VB, NN, TO, JJ, J...   
2      [NN, NNS, NNP, VBD, JJ, NNS, IN, DT, NNP, JJ, ...   
3         [PRP, VBD, IN, DT, NN, JJ, NN, IN, NN, NNS, .]   
4      [NNP, NN, NN, NNP, NNP, VBD, NNP, ,, NNP, ,, J...   
...                                                  ...   
47954  [NNP, NN, NNP, NNP, NNP, VBZ, VBN, PRP, VBZ, T...   
47955  [IN, NNP, ,, JJ, NN, NNS, VBN, DT, NN, IN, DT,...   
47956  [VBG, NNP, POS, JJ, NNP, CD, NNS, ,, NNS, NNS,...   
47957  [IN, RB, ,, NNS, VBP, VBN, JJ, NNS, IN, DT, VB...   
47958  [DT, NNP, NNP, VBZ, VBG, DT, NN, IN, JJ, NNS, ...   

                                                     Tag  
0      [O, O, O, O, O, O, B-geo, O, O, O, O, O, B-geo...  
1      [B-gpe, O, O, O, O, O, O, O, O, O, O, O, O, O,...  
2      [O, O, B-tim, O, O, O, O, O, B-geo, O, O, O, O...  
3                      [O, O, O, O, O, O, O, O, O, O, O]  
4      [B-geo, O, O, B-per, I-per, O, B-tim, O, B-geo...  
...                                                  ...  
47954  [O, O, O, B-per, I-per, O, O, O, O, O, O, O, O...  
47955  [O, B-tim, O, B-gpe, O, O, O, O, O, O, O, O, B...  
47956  [O, B-geo, O, O, B-tim, I-tim, O, O, O, O, O, ...  
47957  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...  
47958  [O, B-org, I-org, O, O, O, O, O, O, O, O, O, O...  

[47959 rows x 4 columns]

In [125]:
grouped_data["Word"] = grouped_data["Word"].apply(lambda x:" ".join(x))

In [126]:
grouped_data = grouped_data.rename(columns={"Sentence":"Sentence_number","Word":"Sentence"})

In [127]:
grouped_data

Sentence_number                                           Sentence  \
0          Sentence: 1  Thousands of demonstrators have marched throug...   
1         Sentence: 10  Iranian officials say they expect to get acces...   
2        Sentence: 100  Helicopter gunships Saturday pounded militant ...   
3       Sentence: 1000  They left after a tense hour-long standoff wit...   
4      Sentence: 10000  U.N. relief coordinator Jan Egeland said Sunda...   
...                ...                                                ...   
47954   Sentence: 9995  Opposition leader Mir Hossein Mousavi has said...   
47955   Sentence: 9996  On Thursday , Iranian state media published a ...   
47956   Sentence: 9997  Following Iran 's disputed June 12 elections ,...   
47957   Sentence: 9998  Since then , authorities have held public tria...   
47958   Sentence: 9999  The United Nations is praising the use of mili...   

                                                     POS  \
0      [NNS, IN, NNS, VBP, VBN, IN, NNP, TO, VB, DT, ...   
1      [JJ, NNS, VBP, PRP, VBP, TO, VB, NN, TO, JJ, J...   
2      [NN, NNS, NNP, VBD, JJ, NNS, IN, DT, NNP, JJ, ...   
3         [PRP, VBD, IN, DT, NN, JJ, NN, IN, NN, NNS, .]   
4      [NNP, NN, NN, NNP, NNP, VBD, NNP, ,, NNP, ,, J...   
...                                                  ...   
47954  [NNP, NN, NNP, NNP, NNP, VBZ, VBN, PRP, VBZ, T...   
47955  [IN, NNP, ,, JJ, NN, NNS, VBN, DT, NN, IN, DT,...   
47956  [VBG, NNP, POS, JJ, NNP, CD, NNS, ,, NNS, NNS,...   
47957  [IN, RB, ,, NNS, VBP, VBN, JJ, NNS, IN, DT, VB...   
47958  [DT, NNP, NNP, VBZ, VBG, DT, NN, IN, JJ, NNS, ...   

                                                     Tag  
0      [O, O, O, O, O, O, B-geo, O, O, O, O, O, B-geo...  
1      [B-gpe, O, O, O, O, O, O, O, O, O, O, O, O, O,...  
2      [O, O, B-tim, O, O, O, O, O, B-geo, O, O, O, O...  
3                      [O, O, O, O, O, O, O, O, O, O, O]  
4      [B-geo, O, O, B-per, I-per, O, B-tim, O, B-geo...  
...                                                  ...  
47954  [O, O, O, B-per, I-per, O, O, O, O, O, O, O, O...  
47955  [O, B-tim, O, B-gpe, O, O, O, O, O, O, O, O, B...  
47956  [O, B-geo, O, O, B-tim, I-tim, O, O, O, O, O, ...  
47957  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...  
47958  [O, B-org, I-org, O, O, O, O, O, O, O, O, O, O...  

[47959 rows x 4 columns]

In [128]:
X = list(grouped_data['Sentence'])
Y = list(grouped_data['Tag'])

In [152]:
X[0]

'Thousands of demonstrators have marched through London to protest the war in Iraq and demand the withdrawal of British troops from that country .'

In [157]:
X

['Thousands of demonstrators have marched through London to protest the war in Iraq and demand the withdrawal of British troops from that country .',
 'Iranian officials say they expect to get access to sealed sensitive parts of the plant Wednesday , after an IAEA surveillance system begins functioning .',
 'Helicopter gunships Saturday pounded militant hideouts in the Orakzai tribal region , where many Taliban militants are believed to have fled to avoid an earlier military offensive in nearby South Waziristan .',
 'They left after a tense hour-long standoff with riot police .',
 'U.N. relief coordinator Jan Egeland said Sunday , U.S. , Indonesian and Australian military helicopters are ferrying out food and supplies to remote areas of western Aceh province that ground crews can not reach .',
 'Mr. Egeland said the latest figures show 1.8 million people are in need of food assistance - with the need greatest in Indonesia , Sri Lanka , the Maldives and India .',
 "He said last week 's 

In [133]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# padding is used to make all data in the input of the same length

#Tokenizer
#Converts the text into a sequence of integers, 
#where each integer represents a word in the text. 

In [135]:
# cutoff reviews after 110 words
maxlen = 110

# consider the top 36000 words in the dataset
max_words = 36000

# tokenize each sentence in the dataset
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(X)
sequences = tokenizer.texts_to_sequences(X)

In [138]:
len(sequences)

47959

In [156]:
sequences

[[260,
  3,
  997,
  13,
  1838,
  245,
  452,
  4,
  545,
  1,
  121,
  2,
  60,
  6,
  595,
  1,
  861,
  3,
  184,
  89,
  21,
  12,
  54],
 [321,
  33,
  26,
  45,
  1810,
  4,
  789,
  1030,
  4,
  4294,
  3221,
  793,
  3,
  1,
  1180,
  82,
  40,
  24,
  1678,
  2237,
  476,
  2238,
  5977],
 [1191,
  4455,
  95,
  4975,
  284,
  4770,
  2,
  1,
  4295,
  790,
  136,
  180,
  199,
  433,
  107,
  28,
  764,
  4,
  13,
  862,
  4,
  1535,
  24,
  139,
  51,
  863,
  2,
  1225,
  114,
  1536],
 [45, 365, 40, 5, 4610, 1018, 322, 3145, 15, 2399, 57],
 [14,
  131,
  659,
  5426,
  1811,
  5200,
  16,
  87,
  14,
  20,
  1138,
  6,
  1079,
  51,
  1758,
  28,
  13669,
  104,
  330,
  6,
  817,
  4,
  1307,
  409,
  3,
  234,
  2078,
  124,
  12,
  1537,
  4456,
  250,
  41,
  1048],
 [35,
  5200,
  16,
  1,
  567,
  1703,
  591,
  155,
  479,
  127,
  39,
  28,
  2,
  909,
  3,
  330,
  945,
  15,
  1,
  909,
  4296,
  2,
  596,
  924,
  1390,
  1,
  8174,
  6,
  239],
 [23,
  16,
  5

In [167]:
word2id = tokenizer.word_index
word2id

{'the': 1,
 'in': 2,
 'of': 3,
 'to': 4,
 'a': 5,
 'and': 6,
 "'s": 7,
 'for': 8,
 'has': 9,
 'on': 10,
 'is': 11,
 'that': 12,
 'have': 13,
 'u': 14,
 'with': 15,
 'said': 16,
 'was': 17,
 'at': 18,
 'says': 19,
 's': 20,
 'from': 21,
 'by': 22,
 'he': 23,
 'an': 24,
 'as': 25,
 'say': 26,
 'it': 27,
 'are': 28,
 'were': 29,
 'his': 30,
 'president': 31,
 'will': 32,
 'officials': 33,
 'government': 34,
 'mr': 35,
 'two': 36,
 'been': 37,
 'killed': 38,
 'people': 39,
 'after': 40,
 'not': 41,
 'its': 42,
 'be': 43,
 'but': 44,
 'they': 45,
 'more': 46,
 'also': 47,
 'year': 48,
 'new': 49,
 'united': 50,
 'military': 51,
 'last': 52,
 'who': 53,
 'country': 54,
 'than': 55,
 'minister': 56,
 'police': 57,
 'one': 58,
 'their': 59,
 'iraq': 60,
 'which': 61,
 'security': 62,
 'this': 63,
 'about': 64,
 'other': 65,
 'states': 66,
 'had': 67,
 'least': 68,
 'state': 69,
 'three': 70,
 'tuesday': 71,
 'week': 72,
 'since': 73,
 'world': 74,
 'forces': 75,
 'thursday': 76,
 'group': 77,


In [168]:
print("Total Unique tockens",len(word2id))
id2word = dict([(value, key) for (key, value) in word2id.items()])
id2word

Total Unique tockens 27953


{1: 'the',
 2: 'in',
 3: 'of',
 4: 'to',
 5: 'a',
 6: 'and',
 7: "'s",
 8: 'for',
 9: 'has',
 10: 'on',
 11: 'is',
 12: 'that',
 13: 'have',
 14: 'u',
 15: 'with',
 16: 'said',
 17: 'was',
 18: 'at',
 19: 'says',
 20: 's',
 21: 'from',
 22: 'by',
 23: 'he',
 24: 'an',
 25: 'as',
 26: 'say',
 27: 'it',
 28: 'are',
 29: 'were',
 30: 'his',
 31: 'president',
 32: 'will',
 33: 'officials',
 34: 'government',
 35: 'mr',
 36: 'two',
 37: 'been',
 38: 'killed',
 39: 'people',
 40: 'after',
 41: 'not',
 42: 'its',
 43: 'be',
 44: 'but',
 45: 'they',
 46: 'more',
 47: 'also',
 48: 'year',
 49: 'new',
 50: 'united',
 51: 'military',
 52: 'last',
 53: 'who',
 54: 'country',
 55: 'than',
 56: 'minister',
 57: 'police',
 58: 'one',
 59: 'their',
 60: 'iraq',
 61: 'which',
 62: 'security',
 63: 'this',
 64: 'about',
 65: 'other',
 66: 'states',
 67: 'had',
 68: 'least',
 69: 'state',
 70: 'three',
 71: 'tuesday',
 72: 'week',
 73: 'since',
 74: 'world',
 75: 'forces',
 76: 'thursday',
 77: 'group',


In [144]:
X_preprocessed = pad_sequences(sequences, maxlen=maxlen, padding='post')

In [176]:
# All the sentence now padded to 110 lengths each 
X_preprocessed[0]

array([ 260,    3,  997,   13, 1838,  245,  452,    4,  545,    1,  121,
          2,   60,    6,  595,    1,  861,    3,  184,   89,   21,   12,
         54,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [ ]:
#For all the input we got word2id and id2 word , now for tag also we have to do tag2id and id2tag

In [169]:
tags = data.Tag.unique()
tags

array(['O', 'B-geo', 'B-gpe', 'B-per', 'I-geo', 'B-org', 'I-org', 'B-tim',
       'B-art', 'I-art', 'I-per', 'I-gpe', 'I-tim', 'B-nat', 'B-eve',
       'I-eve', 'I-nat'], dtype=object)

In [171]:
tags2id = {}
for i, tag in enumerate(tags):
    tags2id[tag] = i

In [172]:
id2tag = {}
for key, value in tags2id.items():
    id2tag[value] = key

In [173]:
tags2id

{'O': 0,
 'B-geo': 1,
 'B-gpe': 2,
 'B-per': 3,
 'I-geo': 4,
 'B-org': 5,
 'I-org': 6,
 'B-tim': 7,
 'B-art': 8,
 'I-art': 9,
 'I-per': 10,
 'I-gpe': 11,
 'I-tim': 12,
 'B-nat': 13,
 'B-eve': 14,
 'I-eve': 15,
 'I-nat': 16}

In [174]:
id2tag

{0: 'O',
 1: 'B-geo',
 2: 'B-gpe',
 3: 'B-per',
 4: 'I-geo',
 5: 'B-org',
 6: 'I-org',
 7: 'B-tim',
 8: 'B-art',
 9: 'I-art',
 10: 'I-per',
 11: 'I-gpe',
 12: 'I-tim',
 13: 'B-nat',
 14: 'B-eve',
 15: 'I-eve',
 16: 'I-nat'}

In [179]:
# As our X processed is ready , we have to ready our y processed by mapping y values to its id's and 
# padding upto 110 length

In [178]:
Y

[['O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-geo',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-geo',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-gpe',
  'O',
  'O',
  'O',
  'O',
  'O'],
 ['B-gpe',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-tim',
  'O',
  'O',
  'O',
  'B-org',
  'O',
  'O',
  'O',
  'O',
  'O'],
 ['O',
  'O',
  'B-tim',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-geo',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-org',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-geo',
  'I-geo',
  'O'],
 ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],
 ['B-geo',
  'O',
  'O',
  'B-per',
  'I-per',
  'O',
  'B-tim',
  'O',
  'B-geo',
  'O',
  'B-gpe',
  'O',
  'B-gpe',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-geo',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O'],
 ['B-per',
  'I-per',
  'O',
  'O',
  'O',
  'O',


In [185]:
numerical_labels = [[tags2id[label] for label in sentence] for sentence in Y]

In [186]:
numerical_labels

[[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
 [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 5, 0, 0, 0, 0, 0],
 [0,
  0,
  7,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  4,
  0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1,
  0,
  0,
  3,
  10,
  0,
  7,
  0,
  1,
  0,
  2,
  0,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [3,
  10,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  7,
  0,
  3,
  2,
  0,
  0,
  1,
  0,
  1,
  0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [2,
  0,
  0,
  0,
  7,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  

In [187]:
Y_preprocessed = pad_sequences(numerical_labels, maxlen=maxlen, padding='post')

In [189]:
Y_preprocessed[0]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int32)

In [190]:
# Now both X and Y are ready to go inside model for training

# Train, Validation, Test split

In [191]:
train_data = 0.7
validation_data = 0.10
test_data = 0.20

In [198]:

# Took reference form chat GPT reference


import numpy as np

def split_data(X, y, train_ratio=0.7, val_ratio=0.1, test_ratio=0.2):

    assert train_ratio + val_ratio + test_ratio == 1, "Ratios should sum up to 1"
    assert len(X) == len(y), "Input features and labels must have the same length"

    # Shuffle the data
    indices = np.random.permutation(len(X))
    X_shuffled = X[indices]
    y_shuffled = y[indices]

    # Calculate split indices
    total_len = len(X)
    train_end = int(total_len * train_ratio)
    val_end = train_end + int(total_len * val_ratio)

    # Split the data
    train_X, train_y = X_shuffled[:train_end], y_shuffled[:train_end]
    val_X, val_y = X_shuffled[train_end:val_end], y_shuffled[train_end:val_end]
    test_X, test_y = X_shuffled[val_end:], y_shuffled[val_end:]

    return train_X, train_y, val_X, val_y, test_X, test_y


train_X, train_y, val_X, val_y, test_X, test_y = split_data(X_preprocessed, Y_preprocessed)

print("Train data shapes - X:", train_X.shape, "y:", train_y.shape)
print("Validation data shapes - X:", val_X.shape, "y:", val_y.shape)
print("Test data shapes - X:", test_X.shape, "y:", test_y.shape)

Train data shapes - X: (33571, 110) y: (33571, 110)
Validation data shapes - X: (4795, 110) y: (4795, 110)
Test data shapes - X: (9593, 110) y: (9593, 110)


In [204]:
import tensorflow as tf

train_dataset = tf.data.Dataset.from_tensor_slices((train_X, train_y))
val_dataset = tf.data.Dataset.from_tensor_slices((val_X, val_y))
test_dataset = tf.data.Dataset.from_tensor_slices((test_X, test_y))

In [205]:
train_X[0]

array([  35, 5200,   19,    1,  523,    9,  765,  102,    4, 1348,  177,
          3,    1,  947,    2,  101,  409,    3,  219, 1930,   21,   59,
        715, 3228,   12,  427,    3,  260,    3, 1142,   28,   18, 4301,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [212]:

#A batch size of 132 means that 132 samples will be processed together in each iteration of training

BATCH_SIZE = 132
SHUFFLE_BUFFER_SIZE = 132

train_dataset = train_dataset.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)
val_dataset = val_dataset.batch(BATCH_SIZE)
test_dataset = test_dataset.batch(BATCH_SIZE)

# Model Building

In [207]:
# Creating and neural network


#In natural language processing (NLP) tasks, words are often represented as dense vectors in an embedding space, 
#and embedding_dim specifies the size of these vectors.

embedding_dim = 300
maxlen = 110 # For each sentence length is 110(less than that will be padded and more will be truncated)
max_words = 36000 # Total words in vocabulaory limit
num_tags = len(tags)  # total distinct tags

model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(max_words, embedding_dim, input_length=maxlen),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(units=100, activation='tanh', return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(units=100, activation='tanh', return_sequences=True)),
    tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(num_tags, activation='softmax'))
])


#A time distributed dense layer takes a batch size by sequence length by input size array and produces 
#a batch size by sequence length by number of classes size array

#model consists of an embedding layer followed by two bidirectional LSTM layers and a time-distributed 
#dense layer for multi-label classification, where each output corresponds to a tag or label.

In [208]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 110, 300)          10800000  
                                                                 
 bidirectional (Bidirection  (None, 110, 200)          320800    
 al)                                                             
                                                                 
 bidirectional_1 (Bidirecti  (None, 110, 200)          240800    
 onal)                                                           
                                                                 
 time_distributed (TimeDist  (None, 110, 17)           3417      
 ributed)                                                        
                                                                 
Total params: 11365017 (43.35 MB)
Trainable params: 11365017 (43.35 MB)
Non-trainable params: 0 (0.00 Byte)
______________

In [215]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])


#This is the loss function used for multi-class classification tasks where the target labels are integers. 
#It calculates the cross-entropy loss between the true labels and the predicted probabilities. 


In [216]:
history = model.fit(train_dataset,
                    validation_data=val_dataset,
                    epochs=30)

Epoch 1/30
255/255 [==============================] - 93s 360ms/step - loss: 0.1961 - accuracy: 0.9696 - val_loss: 0.1589 - val_accuracy: 0.9695
Epoch 2/30
255/255 [==============================] - 90s 351ms/step - loss: 0.1559 - accuracy: 0.9696 - val_loss: 0.1592 - val_accuracy: 0.9695
Epoch 3/30
255/255 [==============================] - 92s 362ms/step - loss: 0.1539 - accuracy: 0.9696 - val_loss: 0.1618 - val_accuracy: 0.9695
Epoch 4/30
255/255 [==============================] - 108s 425ms/step - loss: 0.1513 - accuracy: 0.9696 - val_loss: 0.1652 - val_accuracy: 0.9695
Epoch 5/30
255/255 [==============================] - 112s 439ms/step - loss: 0.1491 - accuracy: 0.9696 - val_loss: 0.1658 - val_accuracy: 0.9695
Epoch 6/30
255/255 [==============================] - 114s 449ms/step - loss: 0.1472 - accuracy: 0.9696 - val_loss: 0.1687 - val_accuracy: 0.9695
Epoch 7/30
255/255 [==============================] - 1857s 7s/step - loss: 0.1459 - accuracy: 0.9696 - val_loss: 0.1736 - val_

In [389]:
model.evaluate(test_dataset)


73/73 [==============================] - 8s 108ms/step - loss: 0.2794 - accuracy: 0.9603


[0.2793729305267334, 0.96028733253479]

# Lets get prediction for one row

In [465]:
test_X[140]

array([   1,  597, 1373,   32,  724,    4,    1, 5005,    3, 3241, 3921,
          6, 8012,    8, 1427,  659,    6,  780,  762,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [466]:
sen = test_X[140].reshape(1,110)
sentence = test_X[140][test_X[140] > 0]

In [467]:
sen

array([[   1,  597, 1373,   32,  724,    4,    1, 5005,    3, 3241, 3921,
           6, 8012,    8, 1427,  659,    6,  780,  762,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [468]:
sentence

array([   1,  597, 1373,   32,  724,    4,    1, 5005,    3, 3241, 3921,
          6, 8012,    8, 1427,  659,    6,  780,  762], dtype=int32)

In [469]:
word_list = []

for word in list(sentence):
    if word in list(id2word.keys()):
        word_list.append(id2word[word])
        
orginal_sentence = ' '.join(word_list)

len_orginal_sentence = len(word_list)        

In [470]:
orginal_sentence

'the money raised will go to the governors of louisiana mississippi and alabama for disaster relief and medical services'

In [471]:
prediction = model.predict(sen)

1/1 [==============================] - 0s 30ms/step


In [472]:
prediction.shape

(1, 110, 17)

In [473]:
prediction

array([[[7.36476839e-01, 1.03457533e-01, 7.26036504e-02, ...,
         9.42946062e-05, 1.27919211e-05, 1.28147785e-05],
        [8.86656165e-01, 1.91250164e-02, 2.90050041e-02, ...,
         5.71358833e-05, 1.68797687e-05, 8.43596172e-06],
        [9.53628659e-01, 1.27823064e-02, 1.35334916e-02, ...,
         3.54624790e-05, 2.50417943e-05, 5.63282720e-06],
        ...,
        [9.99999762e-01, 1.31905047e-08, 8.48112514e-09, ...,
         4.52849536e-10, 1.25753075e-12, 4.99828338e-11],
        [9.99999762e-01, 6.09002981e-09, 4.52352555e-09, ...,
         7.11042225e-10, 1.74387187e-12, 6.36851266e-11],
        [9.99997854e-01, 5.43994503e-08, 1.57547824e-08, ...,
         6.71888358e-08, 1.20695398e-09, 1.67310361e-08]]], dtype=float32)

In [474]:
prediction[0].shape

(110, 17)

In [475]:
prediction_position = np.argmax(prediction[0], axis=1)
prediction_position

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [476]:
prediction_final = list(prediction_position)[ : len_orginal_sentence] 

In [477]:
prediction_final

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [478]:
pred_tag_list = []
for tag_id in prediction_final:
    pred_tag_list.append(id2tag[tag_id])

In [479]:
pred_tag_list

['O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O']